import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ThemeRegistry from '@/src/utils/ThemeRegistry';
import { Providers } from '@/src/utils/redux/provider';
import ReactQueryProvider from '@/src/utils/query/ReactQueryProvider';
import 'react-date-range/dist/styles.css'; // main css file
import 'react-date-range/dist/theme/default.css'; // theme css file

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ReactQueryProvider>
            <ThemeRegistry options={{ key: 'mui-theme' }}>{children}</ThemeRegistry>
          </ReactQueryProvider>
        </Providers>
      </body>
    </html>
  );
}
